/**
 * @fileoverview gRPC-Web generated client stub for message
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: message.proto


/* eslint-disable */
// @ts-nocheck

import './message_pb.js';

const grpc = {};
grpc.web = require('grpc-web');

const global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var exports = {};
global.proto = global.proto || {};
const proto = global.proto;
export { proto };

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */

proto.message.MessageServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.message.MessageServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.message.SendMessageRequest,
 *   !proto.message.SendMessageResponse>}
 */
const methodDescriptor_MessageService_SendMessage = new grpc.web.MethodDescriptor(
  '/message.MessageService/SendMessage',
  grpc.web.MethodType.UNARY,
  proto.message.SendMessageRequest,
  proto.message.SendMessageResponse,
  /**
   * @param {!proto.message.SendMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.message.SendMessageResponse.deserializeBinary
);


/**
 * @param {!proto.message.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.message.SendMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.message.SendMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServiceClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/message.MessageService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_SendMessage,
      callback);
};


/**
 * @param {!proto.message.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.message.SendMessageResponse>}
 *     Promise that resolves to the response
 */
proto.message.MessageServicePromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/message.MessageService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_SendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.message.GetMessagesRequest,
 *   !proto.message.GetMessagesResponse>}
 */
const methodDescriptor_MessageService_GetMessages = new grpc.web.MethodDescriptor(
  '/message.MessageService/GetMessages',
  grpc.web.MethodType.UNARY,
  proto.message.GetMessagesRequest,
  proto.message.GetMessagesResponse,
  /**
   * @param {!proto.message.GetMessagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.message.GetMessagesResponse.deserializeBinary
);


/**
 * @param {!proto.message.GetMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.message.GetMessagesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.message.GetMessagesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServiceClient.prototype.getMessages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/message.MessageService/GetMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_GetMessages,
      callback);
};


/**
 * @param {!proto.message.GetMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.message.GetMessagesResponse>}
 *     Promise that resolves to the response
 */
proto.message.MessageServicePromiseClient.prototype.getMessages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/message.MessageService/GetMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_GetMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.message.ConnectRequest,
 *   !proto.message.MessageResponse>}
 */
const methodDescriptor_MessageService_ConnectMessages = new grpc.web.MethodDescriptor(
  '/message.MessageService/ConnectMessages',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.message.ConnectRequest,
  proto.message.MessageResponse,
  /**
   * @param {!proto.message.ConnectRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.message.MessageResponse.deserializeBinary
);


/**
 * @param {!proto.message.ConnectRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.message.MessageResponse>}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServiceClient.prototype.connectMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/message.MessageService/ConnectMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_ConnectMessages);
};


/**
 * @param {!proto.message.ConnectRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.message.MessageResponse>}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServicePromiseClient.prototype.connectMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/message.MessageService/ConnectMessages',
      request,
      metadata || {},
      methodDescriptor_MessageService_ConnectMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.message.DeleteMessageRequest,
 *   !proto.message.Empty>}
 */
const methodDescriptor_MessageService_DeleteMessage = new grpc.web.MethodDescriptor(
  '/message.MessageService/DeleteMessage',
  grpc.web.MethodType.UNARY,
  proto.message.DeleteMessageRequest,
  proto.message.Empty,
  /**
   * @param {!proto.message.DeleteMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.message.Empty.deserializeBinary
);


/**
 * @param {!proto.message.DeleteMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.message.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.message.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServiceClient.prototype.deleteMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/message.MessageService/DeleteMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_DeleteMessage,
      callback);
};


/**
 * @param {!proto.message.DeleteMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.message.Empty>}
 *     Promise that resolves to the response
 */
proto.message.MessageServicePromiseClient.prototype.deleteMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/message.MessageService/DeleteMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_DeleteMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.message.EditMessageRequest,
 *   !proto.message.Empty>}
 */
const methodDescriptor_MessageService_EditMessage = new grpc.web.MethodDescriptor(
  '/message.MessageService/EditMessage',
  grpc.web.MethodType.UNARY,
  proto.message.EditMessageRequest,
  proto.message.Empty,
  /**
   * @param {!proto.message.EditMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.message.Empty.deserializeBinary
);


/**
 * @param {!proto.message.EditMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.message.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.message.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.message.MessageServiceClient.prototype.editMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/message.MessageService/EditMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_EditMessage,
      callback);
};


/**
 * @param {!proto.message.EditMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.message.Empty>}
 *     Promise that resolves to the response
 */
proto.message.MessageServicePromiseClient.prototype.editMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/message.MessageService/EditMessage',
      request,
      metadata || {},
      methodDescriptor_MessageService_EditMessage);
};


module.exports = proto.message;

