syntax = "proto3";

package contact;

option go_package = "gen/contact;contact";

import "google/api/annotations.proto";

service ContactService {
  rpc SearchUsers(SearchUsersRequest) returns (SearchUsersResponse) {
    option (google.api.http) = {
      get: "/contacts/search"
    };
  }
  
  rpc AddContact(AddContactRequest) returns (AddContactResponse) {
    option (google.api.http) = {
      post: "/contacts"
      body: "*"
    };
  }
  
  rpc GetContacts(GetContactsRequest) returns (GetContactsResponse) {
    option (google.api.http) = {
      get: "/contacts"
    };
  }
  
  rpc DeleteContact(DeleteContactRequest) returns (DeleteContactResponse) {
    option (google.api.http) = {
      delete: "/contacts/{contact_id}"
    };
  }
  
  rpc BlockContact(BlockContactRequest) returns (BlockContactResponse) {
    option (google.api.http) = {
      post: "/contacts/{contact_id}/block"
      body: "*"
    };
  }
}

message User {
  string id = 1;
  string username = 2;
  string email = 3;
}

message SearchUsersRequest {
  string query = 1;
}

message SearchUsersResponse {
  repeated User users = 1;
}

message AddContactRequest {
  string contact_id = 1;
}

message AddContactResponse {
  string message = 1;
}

message GetContactsRequest {}

message GetContactsResponse {
  repeated User contacts = 1;
}

message DeleteContactRequest {
  string contact_id = 1;
}

message DeleteContactResponse {
  string message = 1;
}

message BlockContactRequest {
  string contact_id = 1;
}

message BlockContactResponse {
  string message = 1;
}