syntax = "proto3";

package keys;

option go_package = "gen/keys;keyspb";

service KeyService {
  rpc UploadKeys (UploadKeysRequest) returns (Empty);
  rpc GetPreKeyBundle (GetPreKeyBundleRequest) returns (PreKeyBundle);
  rpc UploadOneTimeKeys(UploadOneTimeKeysRequest) returns (Empty);
  rpc RotateSignedPreKey(RotateSignedPreKeyRequest) returns (Empty);
}

message Empty {}

message UploadKeysRequest {
  string device_id = 1;
  string identity_key_public = 2;
  string signed_prekey_public = 3;
  string signed_prekey_signature = 4;
}

message GetPreKeyBundleRequest {
  string user_id = 1;
}

message PreKeyBundle {
  string user_id = 1;
  string device_id = 2;
  string identity_key_public = 3;
  string signed_prekey_public = 4;
  string signed_prekey_signature = 5;
  string one_time_prekey = 6;
  int32 one_time_prekey_id = 7;
}

message OneTimeKey {
  int32 key_id = 1;
  string public_key = 2;
}

message UploadOneTimeKeysRequest {
  string device_key_id = 1;
  repeated OneTimeKey keys = 2;
}

message RotateSignedPreKeyRequest {
  string device_id = 1;
  string signed_prekey_public = 2;
  string signed_prekey_signature = 3;
}