syntax = "proto3";

package message;

option go_package = "gen/message";

import "google/api/annotations.proto";

service MessageService {
    rpc SendMessage(SendMessageRequest) returns (SendMessageResponse) {
      option (google.api.http) = {
        post: "/messages"
        body: "*"
      };
    }

    rpc GetMessages(GetMessagesRequest) returns (GetMessagesResponse) {
      option (google.api.http) = {
        get: "/chats/{chat_id}/messages"
      };
    }

    rpc ConnectMessages(ConnectRequest) returns (stream MessageResponse);

    rpc DeleteMessage(DeleteMessageRequest) returns (Empty) {
      option (google.api.http) = {
        delete: "/messages/{message_id}"
      };
    }
    
    rpc EditMessage(EditMessageRequest) returns (Empty) {
      option (google.api.http) = {
        put: "/messages/{message_id}"
        body: "*"
      };
    }
}

message ConnectRequest {}

message SendMessageRequest {
    string chat_id = 1;
    string encrypted_content = 2;
}

message SendMessageResponse {
    string message_id = 1;
}

message GetMessagesRequest {
    string chat_id = 1;
}

message MessageResponse {
    string id = 1;
    string chat_id = 2;
    string sender_id = 3;
    string encrypted_content = 4;
    string sent_at = 5;
}

message GetMessagesResponse {
    repeated MessageResponse messages = 1;
}

message DeleteMessageRequest {
    string message_id = 1;
}

message EditMessageRequest {
    string message_id = 1;
    string encrypted_content = 2;
}

message Empty {}